"""add has_sensor to farms

Revision ID: 055b9b0ec553
Revises: c3d4e5f6a7b8
Create Date: 2026-09-10 02:12:49.203868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055b9b0ec553'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('farms')]
    if 'has_sensor' not in columns:
        op.add_column(
            'farms',
            sa.Column(
                'has_sensor',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'has_sensor')
    # ### end Alembic commands ###
